### PR TITLE
feat: adds algorand as formula ENG-572

### PR DESCRIPTION
**Pull request by HashMapsData2Value**
- Adds Algorand as a cask
- Adds CI to automatically update the cask to the latest algorand stable version (checks twice a day)
- Removes macOS-12 for macOS-15 (due to deprecation), and does some small formatting

### CODE REVIEW

**Comment by HashMapsData2Value** [comment]
This solution works. Unfortunately since we don't have code-signing for the algorand binaries, we end up with algod being untrusted. Not exactly the best user experience.

As a result, I will investigate using a formula instead of a cask.

**Comment by HashMapsData2Value** [comment]
Unfortunately due to lack of permissions I am unable to create the data directory in the user's home directory or create a launchctl service. This will need to be handled by hack-tui/algorun.

**Comment by HashMapsData2Value** [comment]
I believe the failing publish-pr is due to this being a merge from a fork.

**Comment by aorumbayev** [comment]
@HashMapsData2Value perhaps try reopening the pr from a branch created on this repo instead of a fork? Credentials accessed from a github auth bot shouldn't crash on that PR trigger in this case. 

Based on the diff, i assume existing workflows are mostly refreshed to support newer runners/actions and do not modify any behaviour in regards to the algokit-cli cask distribution? (See algokit-cli CD pipeline for references on how cli repo triggers PRs when releasing native codesigned binaries to homebrew [here](https://github.com/algorandfoundation/algokit-cli/actions/runs/11575937062/job/32224891953)). Would also suggest refreshing the readme as well to indicate that this repo now hosts multiple casks not just the cli

**Comment by HashMapsData2Value** [comment]
@aorumbayev I will get the required permissions for this repo

**Comment by HashMapsData2Value** [comment]
https://github.com/algorandfoundation/homebrew-tap/pull/90

**Pull request closed without merging**
